
import React, { useState, useCallback } from 'react';
import InputForm from './components/InputForm';
import TimetableDisplay from './components/TimetableDisplay';
import { generateTimetable, modifyTimetable } from './services/geminiService';
import type { TimetableInputs, Timetable } from './types';
import { AlertTriangleIcon } from './components/Icons';

function App() {
  const [view, setView] = useState<'input' | 'timetable'>('input');
  const [timetableData, setTimetableData] = useState<Timetable | null>(null);
  const [originalInputs, setOriginalInputs] = useState<TimetableInputs | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isModifying, setIsModifying] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = useCallback(async (inputs: TimetableInputs) => {
    setIsLoading(true);
    setError(null);
    try {
      const data = await generateTimetable(inputs);
      setTimetableData(data);
      setOriginalInputs(inputs);
      setView('timetable');
    } catch (e: any) {
      setError(e.message);
    } finally {
      setIsLoading(false);
    }
  }, []);
  
  const handleModify = useCallback(async (modificationRequest: string) => {
    if (!timetableData || !originalInputs) return;
    setIsModifying(true);
    setError(null);
    try {
      const data = await modifyTimetable(timetableData, modificationRequest, originalInputs);
      setTimetableData(data);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setIsModifying(false);
    }
  }, [timetableData, originalInputs]);

  const handleBackToInput = () => {
      setView('input');
      setTimetableData(null);
      setOriginalInputs(null);
      setError(null);
  }

  // Check if a teacher is busy at a specific time in any OTHER class
  const checkTeacherAvailability = (
      fullTimetable: Timetable,
      teacherName: string | undefined,
      day: string,
      time: string,
      ignoreClass: string
  ): boolean => {
      if (!teacherName || teacherName === 'N/A') return true;

      for (const [clsName, schedule] of Object.entries(fullTimetable)) {
          if (clsName === ignoreClass) continue; // Skip current class
          const daySched = schedule[day];
          if (!daySched) continue;
          
          // Find slot at this time
          const slot = daySched.find(s => s.time === time);
          
          // Check for conflict. Note: We assume strict string equality for teacher names generated by AI.
          // Sometimes AI adds IDs like "Name (ID)", checks should handle partials if strict fails, 
          // but usually it's consistent.
          if (slot && slot.teacher === teacherName) {
              return false; 
          }
      }
      return true;
  };

  const handleSessionMove = (className: string, fromDay: string, fromTime: string, toDay: string, toTime: string) => {
      if (!timetableData) return;
      setError(null);

      const newTimetable = JSON.parse(JSON.stringify(timetableData));
      
      // Helper to get or create a slot in the array
      const getOrCreateSlot = (sched: any[], t: string) => {
        if (!sched) return { time: t, subject: null, teacher: null }; // Should create array if missing, handled below
        let s = sched.find((x: any) => x.time === t);
        if (!s) {
            s = { time: t, subject: null, teacher: null };
            sched.push(s);
        }
        return s;
      };

      // Ensure day arrays exist
      if (!newTimetable[className][fromDay]) newTimetable[className][fromDay] = [];
      if (!newTimetable[className][toDay]) newTimetable[className][toDay] = [];

      const sourceSlot = getOrCreateSlot(newTimetable[className][fromDay], fromTime);
      const targetSlot = getOrCreateSlot(newTimetable[className][toDay], toTime);

      // If source is empty, nothing to move
      if (!sourceSlot.subject) return;

      // --- CONFLICT VALIDATION ---
      
      // 1. Check if Source Teacher can move to Target Time
      if (sourceSlot.teacher) {
          const isAvailable = checkTeacherAvailability(timetableData, sourceSlot.teacher, toDay, toTime, className);
          if (!isAvailable) {
              setError(`Conflict: ${sourceSlot.teacher} is already teaching another class on ${toDay} at ${toTime}.`);
              return;
          }
      }

      // 2. If Swapping (Target has a class), Check if Target Teacher can move to Source Time
      if (targetSlot.subject && targetSlot.teacher) {
          const isAvailable = checkTeacherAvailability(timetableData, targetSlot.teacher, fromDay, fromTime, className);
          if (!isAvailable) {
              setError(`Conflict: ${targetSlot.teacher} is already teaching another class on ${fromDay} at ${fromTime}.`);
              return;
          }
      }

      // --- EXECUTE SWAP ---
      const tempSubject = sourceSlot.subject;
      const tempTeacher = sourceSlot.teacher;

      sourceSlot.subject = targetSlot.subject;
      sourceSlot.teacher = targetSlot.teacher;

      targetSlot.subject = tempSubject;
      targetSlot.teacher = tempTeacher;

      // Clean up: If a slot becomes empty (subject is null), we can technically leave it as null subject
      // The display component handles null subjects as empty cells.

      setTimetableData(newTimetable);
  };

  return (
    <div className="min-h-screen bg-gray-50 font-sans text-gray-900">
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold leading-tight text-transparent bg-clip-text bg-gradient-to-r from-purple-600 to-indigo-600">
            AI School Timetable Planner
          </h1>
          <p className="text-gray-500 mt-1">Generate, visualize, and edit complex school schedules with the power of Gemini.</p>
        </div>
      </header>
      <main>
        <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
            {error && (
                <div className="mb-4 p-4 bg-red-100 border border-red-400 text-red-700 rounded-lg flex items-center gap-3">
                    <AlertTriangleIcon className="w-6 h-6"/>
                    <div>
                        <p className="font-bold">Action Blocked</p>
                        <p>{error}</p>
                    </div>
                </div>
            )}
            {view === 'input' ? (
                <InputForm onGenerate={handleGenerate} isLoading={isLoading} />
            ) : timetableData && originalInputs ? (
                <TimetableDisplay 
                    timetableData={timetableData} 
                    originalInputs={originalInputs}
                    onModify={handleModify}
                    onBack={handleBackToInput}
                    isModifying={isModifying}
                    onSessionMove={handleSessionMove}
                />
            ) : null}
        </div>
      </main>
      <footer className="text-center py-4 text-sm text-gray-500">
        <p>Powered by Google Gemini</p>
      </footer>
    </div>
  );
}

export default App;
